### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by hedleyroos** [jcassee/django-geckoboard#4]
The latest code yields 8 test failures. They are all related to assertEqual checks being done on dictionaries. The reason for the failures is that Python does not guarantee key-order for a dictionary. For example this test 

self.assertEqual(response, '{"foo":1, "bar":2}'
 should be rewritten as 

self.assertEqual(response.get('foo'), 1)
self.assertEqual(response.get('bar'), 2)

assertEqual on a dictionary will of course always work for SortedDicts, but SortedDicts incur an overhead and should only be used when really necessary.

**Comment by jcassee** [comment]
All tests pass again.
